### GET REQUEST
GET http://localhost:8090/get HTTP/1.1

### GET BY ID
GET http://localhost:8090/get/1 HTTP/1.1

### Create Person
POST http://localhost:8090/create HTTP/1.1

{
    "id": "1",
    "firstName": "Hamdan",
    "lastName": "Suwandi",
    "age": "15"
}

### Update Person
PUT http://localhost:8090/update/{id} HTTP/1.1

{
    "id": "1",
    "firstName": "Hamdan",
    "lastName": "Suwandi",
    "age": "15"
}

### DELETE PERSON
DELETE http://localhost:8090/delete/1 HTTP/1.1